export const getFileUrl = (...args) => {
	return args.length > 1 ? args.join('/') : './' + args;
}

export const getValFromTargetValAndPercent = (percent, total) => {
	return ((percent * total) / 100)
}

export const validateEmail = (email) => {
	var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
	return re.test(email);
}
export const countryCode_phoneNumber = [
	{ "1": "United States: 001" },
	{ "7": "Russia: 007" },
	{ "20": "Egypt: 0020" },
	{ "27": "South Africa: 0027" },
	{ "30": "Greece: 0030" },
	{ "31": "Netherlands: 0031" },
	{ "32": "Belgium: 0032" },
	{ "33": "France: 0033" },
	{ "34": "Spain: 0034" },
	{ "36": "Hungary: 0036" },
	{ "39": "Italy: 0039" },
	{ "40": "Romania: 0040" },
	{ "41": "Switzerland: 0041" },
	{ "43": "Austria: 0043" },
	{ "44": "United Kingdom: 0044" },
	{ "45": "Denmark: 0045" },
	{ "46": "Sweden: 0046" },
	{ "47": "Norway: 0047" },
	{ "48": "Poland: 0048" },
	{ "49": "Germany: 0049" },
	{ "51": "Peru: 0051" },
	{ "52": "Mexico: 0052" },
	{ "53": "Cuba: 0053" },
	{ "54": "Argentina: 0054" },
	{ "55": "Brazil: 0055" },
	{ "56": "Chile: 0056" },
	{ "57": "Colombia: 0057" },
	{ "58": "Venezuela: 0058" },
	{ "60": "Malaysia: 0060" },
	{ "61": "Australia: 0061" },
	{ "62": "Indonesia: 0062" },
	{ "63": "Philippines: 0063" },
	{ "64": "New Zealand: 0064" },
	{ "65": "Singapore: 0065" },
	{ "66": "Thailand: 0066" },
	{ "81": "Japan: 0081" },
	{ "82": "South Korea: 0082" },
	{ "84": "Vietnam: 0084" },
	{ "86": "China: 0086" },
	{ "90": "Turkey: 0090" },
	{ "91": "India: 0091" },
	{ "92": "Pakistan: 0092" },
	{ "93": "Afghanistan: 0093" },
	{ "94": "Sri Lanka: 0094" },
	{ "95": "Myanmar: 0095" },
	{ "98": "Iran: 0098" },
	{ "211": "South Sudan: 00211" },
	{ "212": "Morocco: 00212" },
	{ "213": "Algeria: 00213" },
	{ "216": "Tunisia: 00216" },
	{ "218": "Libya: 00218" },
	{ "220": "The Gambia: 00220" },
	{ "221": "Senegal: 00221" },
	{ "2{22": "Mauritania: 00222" },
	{ "223": "Mali: 00223" },
	{ "224": "Guinea: 00224" },
	{ "225": "Ivory Coast: 00225" },
	{ "226": "Burkina Faso: 00226" },
	{ "227": "Niger: 00227" },
	{ "228": "Togo: 00228" },
	{ "229": "Benin: 00229" },
	{ "230": "Mauritius: 00230" },
	{ "231": "Liberia: 00231" },
	{ "232": "Sierra Leone: 00232" },
	{ "233": "Ghana: 00233" },
	{ "234": "Nigeria: 00234" },
	{ "235": "Chad: 00235" },
	{ "236": "Central African Republic: 00236" },
	{ "237": "Cameroon: 00237" },
	{ "238": "Cape Verde: 00238" },
	{ "239": "Sao Tome and Principe: 00239" },
	{ "240": "Equatorial Guinea: 00240" },
	{ "241": "Gabon: 00241" },
	{ "242": "Republic of the Congo: 00242" },
	{ "243": "Democratic Republic of the Congo: 00243" },
	{ "244": "Angola: 00244" },
	{ "245": "Guinea-Bissau: 00245" },
	{ "246": "British Indian Ocean Territory: 00246" },
	{ "248": "Seychelles: 00248" },
	{ "249": "Sudan: 00249" },
	{ "250": "Rwanda: 00250" },
	{ "251": "Ethiopia: 00251" },
	{ "252": "Somalia: 00252" },
	{ "253": "Djibouti: 00253" },
	{ "254": "Kenya: 00254" },
	{ "255": "Tanzania: 00255" },
	{ "256": "Uganda: 00256" },
	{ "257": "Burundi: 00257" },
	{ "258": "Mozambique: 00258" },
	{ "260": "Zambia: 00260" },
	{ "261": "Madagascar: 00261" },
	{ "262": "R�union: 00262" },
	{ "263": "Zimbabwe: 00263" },
	{ "264": "Namibia: 00264" },
	{ "265": "Malawi: 00265" },
	{ "266": "Lesotho: 00266" },
	{ "267": "Botswana: 00267" },
	{ "268": "Swaziland: 00268" },
	{ "269": "Comoros: 00269" },
	{ "290": "Saint Helena: 00290" },
	{ "291": "Eritrea: 00291" },
	{ "297": "Aruba: 00297" },
	{ "298": "Faroe Islands: 00298" },
	{ "299": "Greenland: 00299" },
	{ "350": "Gibraltar: 00350" },
	{ "351": "Portugal: 00351" },
	{ "352": "Luxembourg: 00352" },
	{ "353": "Ireland: 00353" },
	{ "354": "Iceland: 00354" },
	{ "355": "Albania: 00355" },
	{ "356": "Malta: 00356" },
	{ "357": "Cyprus: 00357" },
	{ "358": "Finland: 00358" },
	{ "359": "Bulgaria: 00359" },
	{ "370": "Lithuania: 00370" },
	{ "371": "Latvia: 00371" },
	{ "372": "Estonia: 00372" },
	{ "373": "Moldova: 00373" },
	{ "374": "Armenia: 00374" },
	{ "375": "Belarus: 00375" },
	{ "376": "Andorra: 00376" },
	{ "377": "Monaco: 00377" },
	{ "378": "San Marino: 00378" },
	{ "380": "Ukraine: 00380" },
	{ "381": "Serbia: 00381" },
	{ "382": "Montenegro: 00382" },
	{ "385": "Croatia: 00385" },
	{ "386": "Slovenia: 00386" },
	{ "387": "Bosnia and Herzegovina: 00387" },
	{ "389": "Macedonia: 00389" },
	{ "420": "Czech Republic: 00420" },
	{ "421": "Slovakia: 00421" },
	{ "423": "Liechtenstein: 00423" },
	{ "500": "Falkland Islands: 00500" },
	{ "501": "Belize: 00501" },
	{ "502": "Guatemala: 00502" },
	{ "503": "El Salvador: 00503" },
	{ "504": "Honduras: 00504" },
	{ "505": "Nicaragua: 00505" },
	{ "506": "Costa Rica: 00506" },
	{ "507": "Panama: 00507" },
	{ "508": "Saint Pierre and Miquelon: 00508" },
	{ "509": "Haiti: 00509" },
	{ "590": "Saint Martin: 00590" },
	{ "591": "Bolivia: 00591" },
	{ "592": "Guyana: 00592" },
	{ "593": "Ecuador: 00593" },
	{ "594": "French Guiana: 00594" },
	{ "595": "Paraguay: 00595" },
	{ "596": "Martinique: 00596" },
	{ "597": "Suriname: 00597" },
	{ "598": "Uruguay: 00598" },
	{ "599": "Sint Maarten: 00599" },
	{ "670": "Timor-Leste: 00670" },
	{ "672": "Norfolk Island: 00672" },
	{ "673": "Brunei: 00673" },
	{ "674": "Nauru: 00674" },
	{ "675": "Papua New Guinea: 00675" },
	{ "676": "Tonga: 00676" },
	{ "677": "Solomon Islands: 00677" },
	{ "678": "Vanuatu: 00678" },
	{ "679": "Fiji: 00679" },
	{ "680": "Palau: 00680" },
	{ "681": "Wallis and Futuna: 00681" },
	{ "682": "Cook Islands: 00682" },
	{ "683": "Niue: 00683" },
	{ "685": "Samoa: 00685" },
	{ "686": "Kiribati: 00686" },
	{ "687": "New Caledonia: 00687" },
	{ "688": "Tuvalu: 00688" },
	{ "689": "French Polynesia: 00689" },
	{ "690": "Tokelau: 00690" },
	{ "691": "Federated States of Micronesia: 00691" },
	{ "692": "Marshall Islands: 00692" },
	{ "850": "North Korea: 00850" },
	{ "852": "Hong Kong: 00852" },
	{ "853": "Macau: 00853" },
	{ "855": "Cambodia: 00855" },
	{ "856": "Laos: 00856" },
	{ "880": "Bangladesh: 00880" },
	{ "886": "Taiwan: 00886" },
	{ "960": "Maldives: 00960" },
	{ "961": "Lebanon: 00961" },
	{ "962": "Jordan: 00962" },
	{ "963": "Syria: 00963" },
	{ "964": "Iraq: 00964" },
	{ "965": "Kuwait: 00965" },
	{ "966": "Saudi Arabia: 00966" },
	{ "967": "Yemen: 00967" },
	{ "968": "Oman: 00968" },
	{ "970": "Palestine: 00970" },
	{ "971": "United Arab Emirates: 00971" },
	{ "972": "Israel: 00972" },
	{ "973": "Bahrain: 00973" },
	{ "974": "Qatar: 00974" },
	{ "975": "Bhutan: 00975" },
	{ "976": "Mongolia: 00976" },
	{ "977": "Nepal: 00977" },
	{ "992": "Tajikistan: 00992" },
	{ "993": "Turkmenistan: 00993" },
	{ "994": "Azerbaijan: 00994" },
	{ "995": "Georgia: 00995" },
	{ "996": "Kyrgyzstan: 00996" },
	{ "998": "Uzbekistan: 00998" }
  ]

export const allcountries =
	[{ "country": "Country..", "code": "" }, { "country": "United Kingdom", "code": "GB" }, { "country": "Qatar", "code": "QA" }, { "country": "Afghanistan", "code": "AF" }, { "country": "Albania", "code": "AL" }, { "country": "Algeria", "code": "DZ" }, { "country": "American Samoa", "code": "AS" }, { "country": "Andorra", "code": "AD" }, { "country": "Angola", "code": "AO" }, { "country": "Anguilla", "code": "AI" }, { "country": "Antarctica", "code": "AQ" }, { "country": "Antigua", "code": "AG" }, { "country": "Argentina", "code": "AR" }, { "country": "Armenia", "code": "AM" }, { "country": "Aruba", "code": "AW" }, { "country": "Australia", "code": "AU" }, { "country": "Austria", "code": "AT" }, { "country": "Azerbaijan", "code": "AZ" }, { "country": "The Bahamas", "code": "BS" }, { "country": "Bahrain", "code": "BH" }, { "country": "Bangladesh", "code": "BD" }, { "country": "Barbados", "code": "BB" }, { "country": "Belarus", "code": "BY" }, { "country": "Belgium", "code": "BE" }, { "country": "Belize", "code": "BZ" }, { "country": "Benin", "code": "BJ" }, { "country": "Bermuda", "code": "BM" }, { "country": "Bhutan", "code": "BT" }, { "country": "Bolivia", "code": "BO" }, { "country": "Bosnia and Herzegovina", "code": "BA" }, { "country": "Botswana", "code": "BW" }, { "country": "Brazil", "code": "BR" }, { "country": "British Indian Ocean Territory", "code": "IO" }, { "country": "British Virgin Islands", "code": "VG" }, { "country": "Brunei", "code": "BN" }, { "country": "Bulgaria", "code": "BG" }, { "country": "Burkina Faso", "code": "BF" }, { "country": "Burundi", "code": "BI" }, { "country": "Cambodia", "code": "KH" }, { "country": "Cameroon", "code": "CM" }, { "country": "Canada", "code": "CA" }, { "country": "Cape Verde", "code": "CV" }, { "country": "Cayman Islands", "code": "KY" }, { "country": "Central African Republic", "code": "CF" }, { "country": "Chad", "code": "TD" }, { "country": "Chile", "code": "CL" }, { "country": "China", "code": "CN" }, { "country": "Christmas Island", "code": "CX" }, { "country": "Cocos Islands", "code": "CC" }, { "country": "Colombia", "code": "CO" }, { "country": "Comoros", "code": "KM" }, { "country": "Cook Islands", "code": "CK" }, { "country": "Costa Rica", "code": "CR" }, { "country": "Croatia", "code": "HR" }, { "country": "Cuba", "code": "CU" }, { "country": "Curacao", "code": "CW" }, { "country": "Cyprus", "code": "CY" }, { "country": "Czech Republic", "code": "CZ" }, { "country": "Democratic Republic of Congo", "code": "CD" }, { "country": "Denmark", "code": "DK" }, { "country": "Djibouti", "code": "DJ" }, { "country": "Dominica", "code": "DM" }, { "country": "Dominican Republic", "code": "DO" }, { "country": "East Timor", "code": "TL" }, { "country": "Ecuador", "code": "EC" }, { "country": "Egypt", "code": "EG" }, { "country": "El Salvador", "code": "SV" }, { "country": "Equatorial Guinea", "code": "GQ" }, { "country": "Eritrea", "code": "ER" }, { "country": "Estonia", "code": "EE" }, { "country": "Ethiopia", "code": "ET" }, { "country": "Falkland Islands", "code": "FK" }, { "country": "Faroe Islands", "code": "FO" }, { "country": "Fiji", "code": "FJ" }, { "country": "Finland", "code": "FI" }, { "country": "France", "code": "FR" }, { "country": "French Polynesia", "code": "PF" }, { "country": "Gabon", "code": "GA" }, { "country": "Gambia", "code": "GM" }, { "country": "Georgia", "code": "GE" }, { "country": "Germany", "code": "DE" }, { "country": "Ghana", "code": "GH" }, { "country": "Gibraltar", "code": "GI" }, { "country": "Greece", "code": "GR" }, { "country": "Greenland", "code": "GL" }, { "country": "Grenada", "code": "GD" }, { "country": "Guam", "code": "GU" }, { "country": "Guatemala", "code": "GT" }, { "country": "Guernsey", "code": "GG" }, { "country": "Guinea", "code": "GN" }, { "country": "Guinea-Bissau", "code": "GW" }, { "country": "Guyana", "code": "GY" }, { "country": "Haiti", "code": "HT" }, { "country": "Honduras", "code": "HN" }, { "country": "Hong Kong", "code": "HK" }, { "country": "Hungary", "code": "HU" }, { "country": "Iceland", "code": "IS" }, { "country": "India", "code": "IN" }, { "country": "Indonesia", "code": "ID" }, { "country": "Iran", "code": "IR" }, { "country": "Iraq", "code": "IQ" }, { "country": "Ireland", "code": "IE" }, { "country": "Isle of Man", "code": "IM" }, { "country": "Italy", "code": "IT" }, { "country": "Ivory Coast", "code": "CI" }, { "country": "Jamaica", "code": "JM" }, { "country": "Japan", "code": "JP" }, { "country": "Jersey", "code": "JE" }, { "country": "Jordan", "code": "JO" }, { "country": "Kazakhstan", "code": "KZ" }, { "country": "Kenya", "code": "KE" }, { "country": "Kiribati", "code": "KI" }, { "country": "Kosovo", "code": "XK" }, { "country": "Kuwait", "code": "KW" }, { "country": "Kyrgyzstan", "code": "KG" }, { "country": "Laos", "code": "LA" }, { "country": "Latvia", "code": "LV" }, { "country": "Lebanon", "code": "LB" }, { "country": "Lesotho", "code": "LS" }, { "country": "Liberia", "code": "LR" }, { "country": "Libya", "code": "LY" }, { "country": "Liechtenstein", "code": "LI" }, { "country": "Lithuania", "code": "LT" }, { "country": "Luxembourg", "code": "LU" }, { "country": "Macau", "code": "MO" }, { "country": "Macedonia", "code": "MK" }, { "country": "Madagascar", "code": "MG" }, { "country": "Malawi", "code": "MW" }, { "country": "Malaysia", "code": "MY" }, { "country": "Maldives", "code": "MV" }, { "country": "Mali", "code": "ML" }, { "country": "Malta", "code": "MT" }, { "country": "Marshall Islands", "code": "MH" }, { "country": "Mauritania", "code": "MR" }, { "country": "Mauritius", "code": "MU" }, { "country": "Mayotte", "code": "YT" }, { "country": "Mexico", "code": "MX" }, { "country": "Micronesia", "code": "FM" }, { "country": "Moldova", "code": "MD" }, { "country": "Monaco", "code": "MC" }, { "country": "Mongolia", "code": "MN" }, { "country": "Montenegro", "code": "ME" }, { "country": "Montserrat", "code": "MS" }, { "country": "Morocco", "code": "MA" }, { "country": "Mozambique", "code": "MZ" }, { "country": "Myanmar", "code": "MM" }, { "country": "Namibia", "code": "NA" }, { "country": "Nauru", "code": "NR" }, { "country": "Nepal", "code": "NP" }, { "country": "Netherlands", "code": "NL" }, { "country": "Netherlands Antilles", "code": "AN" }, { "country": "New Caledonia", "code": "NC" }, { "country": "New Zealand", "code": "NZ" }, { "country": "Nicaragua", "code": "NI" }, { "country": "Niger", "code": "NE" }, { "country": "Nigeria", "code": "NG" }, { "country": "Niue", "code": "NU" }, { "country": "North Korea", "code": "KP" }, { "country": "Northern Mariana Islands", "code": "MP" }, { "country": "Norway", "code": "NO" }, { "country": "Oman", "code": "OM" }, { "country": "Pakistan", "code": "PK" }, { "country": "Palau", "code": "PW" }, { "country": "Palestine", "code": "PS" }, { "country": "Panama", "code": "PA" }, { "country": "Papua New Guinea", "code": "PG" }, { "country": "Paraguay", "code": "PY" }, { "country": "Peru", "code": "PE" }, { "country": "Philippines", "code": "PH" }, { "country": "Pitcairn", "code": "PN" }, { "country": "Poland", "code": "PL" }, { "country": "Portugal", "code": "PT" }, { "country": "Puerto Rico", "code": "PR" }, { "country": "Republic of the Congo", "code": "CG" }, { "country": "Réunion", "code": "RE" }, { "country": "Romania", "code": "RO" }, { "country": "Russia", "code": "RU" }, { "country": "Rwanda", "code": "RW" }, { "country": "Saint Barthélemy", "code": "BL" }, { "country": "Saint Helena", "code": "SH" }, { "country": "Saint Kitts and Nevis", "code": "KN" }, { "country": "Saint Lucia", "code": "LC" }, { "country": "Saint Martin", "code": "MF" }, { "country": "Saint Pierre and Miquelon", "code": "PM" }, { "country": "Saint Vincent and the Grenadines", "code": "VC" }, { "country": "Samoa", "code": "WS" }, { "country": "San Marino", "code": "SM" }, { "country": "São Tomé and Príncipe", "code": "ST" }, { "country": "Saudi Arabia", "code": "SA" }, { "country": "Senegal", "code": "SN" }, { "country": "Serbia", "code": "RS" }, { "country": "Seychelles", "code": "SC" }, { "country": "Sierra Leone", "code": "SL" }, { "country": "Singapore", "code": "SG" }, { "country": "Sint Maarten", "code": "SX" }, { "country": "Slovakia", "code": "SK" }, { "country": "Slovenia", "code": "SI" }, { "country": "Solomon Islands", "code": "SB" }, { "country": "Somalia", "code": "SO" }, { "country": "South Africa", "code": "ZA" }, { "country": "South Korea", "code": "KR" }, { "country": "South Sudan", "code": "SS" }, { "country": "Spain", "code": "ES" }, { "country": "Sri Lanka", "code": "LK" }, { "country": "Sudan", "code": "SD" }, { "country": "Suriname", "code": "SR" }, { "country": "Svalbard and Jan Mayen", "code": "SJ" }, { "country": "Swaziland", "code": "SZ" }, { "country": "Sweden", "code": "SE" }, { "country": "Switzerland", "code": "CH" }, { "country": "Syria", "code": "SY" }, { "country": "Taiwan", "code": "TW" }, { "country": "Tajikistan", "code": "TJ" }, { "country": "Tanzania", "code": "TZ" }, { "country": "Thailand", "code": "TH" }, { "country": "Togo", "code": "TG" }, { "country": "Tokelau", "code": "TK" }, { "country": "Tonga", "code": "TO" }, { "country": "Trinidad and Tobago", "code": "TT" }, { "country": "Tunisia", "code": "TN" }, { "country": "Turkey", "code": "TR" }, { "country": "Turkmenistan", "code": "TM" }, { "country": "Turks and Caicos Islands", "code": "TC" }, { "country": "Tuvalu", "code": "TV" }, { "country": "U.S. Virgin Islands", "code": "VI" }, { "country": "Uganda", "code": "UG" }, { "country": "Ukraine", "code": "UA" }, { "country": "United Arab Emirates", "code": "AE" }, { "country": "United States", "code": "US" }, { "country": "Uruguay", "code": "UY" }, { "country": "Uzbekistan", "code": "UZ" }, { "country": "Vanuatu", "code": "VU" }, { "country": "Vatican City", "code": "VA" }, { "country": "Venezuela", "code": "VE" }, { "country": "Vietnam", "code": "VN" }, { "country": "Wallis and Futuna", "code": "WF" }, { "country": "Western Sahara", "code": "EH" }, { "country": "Yemen", "code": "YE" }, { "country": "Zambia", "code": "ZM" }, { "country": "Zimbabwe", "code": "ZW" }, { "country": "Country..", "code": "" }, { "country": "United Kingdom", "code": "GB" }, { "country": "Qatar", "code": "QA" }, { "country": "Afghanistan", "code": "AF" }, { "country": "Albania", "code": "AL" }, { "country": "Algeria", "code": "DZ" }, { "country": "American Samoa", "code": "AS" }, { "country": "Andorra", "code": "AD" }, { "country": "Angola", "code": "AO" }, { "country": "Anguilla", "code": "AI" }, { "country": "Antarctica", "code": "AQ" }, { "country": "Antigua", "code": "AG" }, { "country": "Argentina", "code": "AR" }, { "country": "Armenia", "code": "AM" }, { "country": "Aruba", "code": "AW" }, { "country": "Australia", "code": "AU" }, { "country": "Austria", "code": "AT" }, { "country": "Azerbaijan", "code": "AZ" }, { "country": "The Bahamas", "code": "BS" }, { "country": "Bahrain", "code": "BH" }, { "country": "Bangladesh", "code": "BD" }, { "country": "Barbados", "code": "BB" }, { "country": "Belarus", "code": "BY" }, { "country": "Belgium", "code": "BE" }, { "country": "Belize", "code": "BZ" }, { "country": "Benin", "code": "BJ" }, { "country": "Bermuda", "code": "BM" }, { "country": "Bhutan", "code": "BT" }, { "country": "Bolivia", "code": "BO" }, { "country": "Bosnia and Herzegovina", "code": "BA" }, { "country": "Botswana", "code": "BW" }, { "country": "Brazil", "code": "BR" }, { "country": "British Indian Ocean Territory", "code": "IO" }, { "country": "British Virgin Islands", "code": "VG" }, { "country": "Brunei", "code": "BN" }, { "country": "Bulgaria", "code": "BG" }, { "country": "Burkina Faso", "code": "BF" }, { "country": "Burundi", "code": "BI" }, { "country": "Cambodia", "code": "KH" }, { "country": "Cameroon", "code": "CM" }, { "country": "Canada", "code": "CA" }, { "country": "Cape Verde", "code": "CV" }, { "country": "Cayman Islands", "code": "KY" }, { "country": "Central African Republic", "code": "CF" }, { "country": "Chad", "code": "TD" }, { "country": "Chile", "code": "CL" }, { "country": "China", "code": "CN" }, { "country": "Christmas Island", "code": "CX" }, { "country": "Cocos Islands", "code": "CC" }, { "country": "Colombia", "code": "CO" }, { "country": "Comoros", "code": "KM" }, { "country": "Cook Islands", "code": "CK" }, { "country": "Costa Rica", "code": "CR" }, { "country": "Croatia", "code": "HR" }, { "country": "Cuba", "code": "CU" }, { "country": "Curacao", "code": "CW" }, { "country": "Cyprus", "code": "CY" }, { "country": "Czech Republic", "code": "CZ" }, { "country": "Democratic Republic of Congo", "code": "CD" }, { "country": "Denmark", "code": "DK" }, { "country": "Djibouti", "code": "DJ" }, { "country": "Dominica", "code": "DM" }, { "country": "Dominican Republic", "code": "DO" }, { "country": "East Timor", "code": "TL" }, { "country": "Ecuador", "code": "EC" }, { "country": "Egypt", "code": "EG" }, { "country": "El Salvador", "code": "SV" }, { "country": "Equatorial Guinea", "code": "GQ" }, { "country": "Eritrea", "code": "ER" }, { "country": "Estonia", "code": "EE" }, { "country": "Ethiopia", "code": "ET" }, { "country": "Falkland Islands", "code": "FK" }, { "country": "Faroe Islands", "code": "FO" }, { "country": "Fiji", "code": "FJ" }, { "country": "Finland", "code": "FI" }, { "country": "France", "code": "FR" }, { "country": "French Polynesia", "code": "PF" }, { "country": "Gabon", "code": "GA" }, { "country": "Gambia", "code": "GM" }, { "country": "Georgia", "code": "GE" }, { "country": "Germany", "code": "DE" }, { "country": "Ghana", "code": "GH" }, { "country": "Gibraltar", "code": "GI" }, { "country": "Greece", "code": "GR" }, { "country": "Greenland", "code": "GL" }, { "country": "Grenada", "code": "GD" }, { "country": "Guam", "code": "GU" }, { "country": "Guatemala", "code": "GT" }, { "country": "Guernsey", "code": "GG" }, { "country": "Guinea", "code": "GN" }, { "country": "Guinea-Bissau", "code": "GW" }, { "country": "Guyana", "code": "GY" }, { "country": "Haiti", "code": "HT" }, { "country": "Honduras", "code": "HN" }, { "country": "Hong Kong", "code": "HK" }, { "country": "Hungary", "code": "HU" }, { "country": "Iceland", "code": "IS" }, { "country": "India", "code": "IN" }, { "country": "Indonesia", "code": "ID" }, { "country": "Iran", "code": "IR" }, { "country": "Iraq", "code": "IQ" }, { "country": "Ireland", "code": "IE" }, { "country": "Isle of Man", "code": "IM" }, { "country": "Italy", "code": "IT" }, { "country": "Ivory Coast", "code": "CI" }, { "country": "Jamaica", "code": "JM" }, { "country": "Japan", "code": "JP" }, { "country": "Jersey", "code": "JE" }, { "country": "Jordan", "code": "JO" }, { "country": "Kazakhstan", "code": "KZ" }, { "country": "Kenya", "code": "KE" }, { "country": "Kiribati", "code": "KI" }, { "country": "Kosovo", "code": "XK" }, { "country": "Kuwait", "code": "KW" }, { "country": "Kyrgyzstan", "code": "KG" }, { "country": "Laos", "code": "LA" }, { "country": "Latvia", "code": "LV" }, { "country": "Lebanon", "code": "LB" }, { "country": "Lesotho", "code": "LS" }, { "country": "Liberia", "code": "LR" }, { "country": "Libya", "code": "LY" }, { "country": "Liechtenstein", "code": "LI" }, { "country": "Lithuania", "code": "LT" }, { "country": "Luxembourg", "code": "LU" }, { "country": "Macau", "code": "MO" }, { "country": "Macedonia", "code": "MK" }, { "country": "Madagascar", "code": "MG" }, { "country": "Malawi", "code": "MW" }, { "country": "Malaysia", "code": "MY" }, { "country": "Maldives", "code": "MV" }, { "country": "Mali", "code": "ML" }, { "country": "Malta", "code": "MT" }, { "country": "Marshall Islands", "code": "MH" }, { "country": "Mauritania", "code": "MR" }, { "country": "Mauritius", "code": "MU" }, { "country": "Mayotte", "code": "YT" }, { "country": "Mexico", "code": "MX" }, { "country": "Micronesia", "code": "FM" }, { "country": "Moldova", "code": "MD" }, { "country": "Monaco", "code": "MC" }, { "country": "Mongolia", "code": "MN" }, { "country": "Montenegro", "code": "ME" }, { "country": "Montserrat", "code": "MS" }, { "country": "Morocco", "code": "MA" }, { "country": "Mozambique", "code": "MZ" }, { "country": "Myanmar", "code": "MM" }, { "country": "Namibia", "code": "NA" }, { "country": "Nauru", "code": "NR" }, { "country": "Nepal", "code": "NP" }, { "country": "Netherlands", "code": "NL" }, { "country": "Netherlands Antilles", "code": "AN" }, { "country": "New Caledonia", "code": "NC" }, { "country": "New Zealand", "code": "NZ" }, { "country": "Nicaragua", "code": "NI" }, { "country": "Niger", "code": "NE" }, { "country": "Nigeria", "code": "NG" }, { "country": "Niue", "code": "NU" }, { "country": "North Korea", "code": "KP" }, { "country": "Northern Mariana Islands", "code": "MP" }, { "country": "Norway", "code": "NO" }, { "country": "Oman", "code": "OM" }, { "country": "Pakistan", "code": "PK" }, { "country": "Palau", "code": "PW" }, { "country": "Palestine", "code": "PS" }, { "country": "Panama", "code": "PA" }, { "country": "Papua New Guinea", "code": "PG" }, { "country": "Paraguay", "code": "PY" }, { "country": "Peru", "code": "PE" }, { "country": "Philippines", "code": "PH" }, { "country": "Pitcairn", "code": "PN" }, { "country": "Poland", "code": "PL" }, { "country": "Portugal", "code": "PT" }, { "country": "Puerto Rico", "code": "PR" }, { "country": "Republic of the Congo", "code": "CG" }, { "country": "Réunion", "code": "RE" }, { "country": "Romania", "code": "RO" }, { "country": "Russia", "code": "RU" }, { "country": "Rwanda", "code": "RW" }, { "country": "Saint Barthélemy", "code": "BL" }, { "country": "Saint Helena", "code": "SH" }, { "country": "Saint Kitts and Nevis", "code": "KN" }, { "country": "Saint Lucia", "code": "LC" }, { "country": "Saint Martin", "code": "MF" }, { "country": "Saint Pierre and Miquelon", "code": "PM" }, { "country": "Saint Vincent and the Grenadines", "code": "VC" }, { "country": "Samoa", "code": "WS" }, { "country": "San Marino", "code": "SM" }, { "country": "São Tomé and Príncipe", "code": "ST" }, { "country": "Saudi Arabia", "code": "SA" }, { "country": "Senegal", "code": "SN" }, { "country": "Serbia", "code": "RS" }, { "country": "Seychelles", "code": "SC" }, { "country": "Sierra Leone", "code": "SL" }, { "country": "Singapore", "code": "SG" }, { "country": "Sint Maarten", "code": "SX" }, { "country": "Slovakia", "code": "SK" }, { "country": "Slovenia", "code": "SI" }, { "country": "Solomon Islands", "code": "SB" }, { "country": "Somalia", "code": "SO" }, { "country": "South Africa", "code": "ZA" }, { "country": "South Korea", "code": "KR" }, { "country": "South Sudan", "code": "SS" }, { "country": "Spain", "code": "ES" }, { "country": "Sri Lanka", "code": "LK" }, { "country": "Sudan", "code": "SD" }, { "country": "Suriname", "code": "SR" }, { "country": "Svalbard and Jan Mayen", "code": "SJ" }, { "country": "Swaziland", "code": "SZ" }, { "country": "Sweden", "code": "SE" }, { "country": "Switzerland", "code": "CH" }, { "country": "Syria", "code": "SY" }, { "country": "Taiwan", "code": "TW" }, { "country": "Tajikistan", "code": "TJ" }, { "country": "Tanzania", "code": "TZ" }, { "country": "Thailand", "code": "TH" }, { "country": "Togo", "code": "TG" }, { "country": "Tokelau", "code": "TK" }, { "country": "Tonga", "code": "TO" }, { "country": "Trinidad and Tobago", "code": "TT" }, { "country": "Tunisia", "code": "TN" }, { "country": "Turkey", "code": "TR" }, { "country": "Turkmenistan", "code": "TM" }, { "country": "Turks and Caicos Islands", "code": "TC" }, { "country": "Tuvalu", "code": "TV" }, { "country": "U.S. Virgin Islands", "code": "VI" }, { "country": "Uganda", "code": "UG" }, { "country": "Ukraine", "code": "UA" }, { "country": "United Arab Emirates", "code": "AE" }, { "country": "United States", "code": "US" }, { "country": "Uruguay", "code": "UY" }, { "country": "Uzbekistan", "code": "UZ" }, { "country": "Vanuatu", "code": "VU" }, { "country": "Vatican City", "code": "VA" }, { "country": "Venezuela", "code": "VE" }, { "country": "Vietnam", "code": "VN" }, { "country": "Wallis and Futuna", "code": "WF" }, { "country": "Western Sahara", "code": "EH" }, { "country": "Yemen", "code": "YE" }, { "country": "Zambia", "code": "ZM" }, { "country": "Zimbabwe", "code": "ZW" }];


